[platformio]


[env]
platform = atmelavr
board = ATmega328P
upload_protocol = usbasp
upload_flags =
    -B
    10
monitor_speed = 9600
lib_ldf_mode = chain+
board_build.compile_commands = yes
board_build.f_cpu = 16000000L


; [env:bootloader]
; build_src_filter =
;   -<*>
;   +<bootloader/*>

[env:gpio]
build_src_filter =
  -<*>
  +<gpio/*>

; [env:uart]
; platform = atmelavr
; board = uno
; framework = arduino
; monitor_speed = 9600
; build_src_filter =
;   -<*>
;   +<uart/*>
; lib_ignore = uart_hal

; [env:spiMaster]
; build_src_filter =
;   -<*>
;   +<spiMaster/*>

; [env:i2cMaster]
; build_src_filter =
;   -<*>
;   +<i2cMaster/*>
