[platformio]

[env:bootloader]
platform = atmelavr
board = uno
upload_protocol = usbasp

board_build.f_cpu = 16000000L
board_build.compile_commands = yes

build_src_filter =
    +<bootloader/>
    -<gpio/>
    -<i2cMaster/>
    -<uart/>

build_flags =
    -Wl,-Ttext=0x7C00

board_fuses.lfuse = 0xFF
board_fuses.hfuse = 0xDC
board_fuses.efuse = 0xFD

upload_flags =
    -B
    10
    -e

monitor_speed = 9600
lib_ldf_mode = chain+



; For normal ISP programming:
; [env]
; platform = atmelavr
; board = uno
; upload_protocol = usbasp
; upload_flags =
;     -B
;     10
;     -e
; monitor_speed = 9600
; lib_ldf_mode = chain+
; board_build.compile_commands = yes
; board_build.f_cpu = 16000000L

; [env:gpio]
; build_src_filter =
;   -<*>
;   +<gpio/*>

; [env:uart]
; platform = atmelavr
; board = uno
; framework = arduino
; monitor_speed = 9600
; build_src_filter =
;   -<*>
;   +<uart/*>
; lib_ignore = uart_hal

; [env:spiMaster]
; build_src_filter =
;   -<*>
;   +<spiMaster/*>

; [env:i2cMaster]
; build_src_filter =
;   -<*>
;   +<i2cMaster/*>
